language: node_js

node_js:
  - stable

install:
  - yarn install

script:
  - npm run coverall

# Send coverage data to Coveralls
after_script: "cat coverage/xliffmerge/lcov.info | node_modules/coveralls/bin/coveralls.js && cat coverage/tooling/lcov.info | node_modules/coveralls/bin/coveralls.js"